"""
Django settings for djangoproject project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'some-secret-key' #saved in git.txt
#wondering why my secret key didn't change

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [


    #3rd Party Resources
    'django_comments_xtd',
    'django_comments',
    'ckeditor',
    'ckeditor_uploader',
    'materialize',
    'bootstrap4',

    #preinstalled apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #My Apps
    'posts',        #new

    #Preinstalled but appended later
    'django.contrib.sites',
]

SITE_ID = 1

COMMENTS_APP = 'django_comments_xtd'
COMMENTS_XTD_CONFIRM_MAIL = False
COMMENTS_XTD_SALT = (b"Ignorance is the cause. "
                     b"In difficult situations, remember to keep in mind.")

COMMENTS_XTD_FROM_EMAIL = "noreply@example.com"

MANAGERS =(
    'Andile Mbele', 'andilembele@zenmedia.com'
)

COMMENT_XTD_CONFIRM_EMAIL = False
COMMENTS_XTD_MAX_THREAD_LEVEL = 1 # default is 0
COMMENTS_XTD_LIST_ORDER = ('-thread_id', 'order') # default id ('thread_id', 'order')

#Contact mail address used to show in messages
COMMENTS_XTD_CONTACT_EMAIL = "helpdesk@example.com"

#Email backend
EMAIL_BACKEND = 'django.core.email.backends.console.EmailBackend'

#Setup EMAIL_ so  taht Django can send emails:
EMAIL_HOST = "smtp.mail.com"
EMAIL_PORT = "587"
EMAIL_HOST_USER = "andilembele020@gmail.com"
EMAIL_HOST_PASSWORD = "qwerty@2010"
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "Helpdesk <helpdesk@yourdomain>"

CKEDITOR_UPLOAD_PATH = "uploads/"

#This defines how CKEditor will display it's window editing tool
# CKEDITOR_CONFIGS = {
#     'default' : {
#         'toolbar' : 'Custom',
#         'height' : 500,
#         'toolbar_custom' : [
#             ['Bold', 'Link', 'Image', 'Italic', 'Underline']
#         ],
#     }
#     'special' : {
#         'toolbar' : 'Custom',
#         'height' : 500,
#         'toolbar_custom' : [
#         ['Bold'],
#     ],
#     }

# }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], #new
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#       'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}


DATABASES = {
    'default' :{
        'ENGINE': 'django.db.backends.mysql',
        'NAME' : 'djangoproject',
        'USER' : 'XeroxZen',
        'PASSWORD' : '2019',
        'HOST' : '127.0.0.1',
        'PORT' : '3306',
        'TIME_ZONE' : 'UTC'

    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CKEDITOR_UPLOAD_PATH = 'uploads/'
